# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mme_tools}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcel Massana"]
  s.date = %q{2011-09-17}
  s.description = %q{generic classes and methods that may be used everywhere}
  s.email = %q{xaxaupua@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "examples/demo_args_proc.rb",
    "examples/demo_config.rb",
    "examples/demo_enumerable.rb",
    "examples/demo_print_debug.rb",
    "examples/demo_webparse.rb",
    "lib/mme_tools.rb",
    "lib/mme_tools/args_proc.rb",
    "lib/mme_tools/concurrent.rb",
    "lib/mme_tools/config.rb",
    "lib/mme_tools/debug.rb",
    "lib/mme_tools/enumerable.rb",
    "lib/mme_tools/version.rb",
    "lib/mme_tools/webparse.rb",
    "mme_tools.gemspec",
    "test/tc_enumerable.rb",
    "test/tc_webparse.rb",
    "test/test_mme_tools.rb"
  ]
  s.homepage = %q{http://github.com/syborg/mme_tools}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{various homeless methods}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<unicode>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
    else
      s.add_dependency(%q<unicode>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
    end
  else
    s.add_dependency(%q<unicode>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
  end
end

